build_info();

load(solve_alt)$

/* load("myload.lisp")$ */

file_search_tests : append(file_search_maxima, file_search_tests)$

push(["rtest_solve2", [15, 16, 18, 19, 20, 22, 30, 46, 66, 69]], testsuite_files)$

push(["rtest_solve",[88, 214, 260, 287, 295, 327, 340, 342, 343,
     351, 376, 395, 396, 397, 398,
     399, 400, 455, 470, 471, 472, 485,
     500, 512, 514, 521, 524, 525, 538, 544, 553, 558, 574, 575, 581, 582, 583,
     584, 585]],testsuite_files)$

push("rtest_linsolve", testsuite_files)$

push("rtest_polynomial_solve",testsuite_files)$

push(["rtest_wester_equations", [14, 15, 31, 32, 55, 60, 65]], testsuite_files)$

push(["rtest_inverses",[19]],testsuite_files)$

push(["rtest_extra_solve", [19]], testsuite_files)$

run_testsuite(share_tests = true);
