build_info();

load(solve_alt)$

/* load("myload.lisp")$ */

file_search_tests : append(file_search_maxima, file_search_tests)$

push(["rtest_solve2", [14, 15, 16, 19, 22, 30, 46, 66, 69]], testsuite_files)$

push(["rtest_solve",[214, 260, 287, 295, 326, 327, 340, 342, 343,
     376, 395, 396, 397, 398,
     400, 470, 472, 485,
     500, 512, 514, 525, 538, 544, 553, 558, 574, 575, 581, 582, 583,
     584, 585]],testsuite_files)$

push("rtest_linsolve", testsuite_files)$

push("rtest_polynomial_solve",testsuite_files)$

push(["rtest_wester_equations", [13, 14, 30, 31, 64, 69]], testsuite_files)$

push(["rtest_inverses",[]],testsuite_files)$

push(["rtest_extra_solve", []], testsuite_files)$

push(["rtest_mcond_solve", [8]], testsuite_files)$

push(["rtest_algebraic_solve", []], testsuite_files)$

run_testsuite(share_tests = true);
